
# Syntax highlighting
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#permalink:           /:title
#relative_permalinks: true
permalink:            pretty
#permalink:           /findtrip/findtrip/:year/:month/:day/:title/

# Deploy
github:              https://github.com/ilmesi/findtrip

# Setup
timezone:            Europe/Barcelona
locale:              es_es
name:				         Findtrip
title:               Encuentra salidas divertidas cerca de Barcelona!
tagline:             'tagline'
description:         'description'
url:                 findtrip.co
rss:                 rss feed url
baseurl:             '/'
baseurl_icons_img:   '/assets/images/icons/'
baseurl_routes_img:   '/assets/images/routes/'
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/cities/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts: '/assets/javascripts/'
icon:                your site icon path # /assets/img/icon.png [best 300px X 300px]
disqus:              findtrip # get it on https://disqus.com/admin/

author:
  name:           	 Findtrip
  url:            	 findtrip.co
  facebook:          username
  twitter:           username

fb_admins:           your facebook profile id
fb_appid:            your facebook app id

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
